services:
  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  postgres:
    image: postgres:15
    container_name: sms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smsdb
      POSTGRES_USER: smsuser
      POSTGRES_PASSWORD: smspass
    volumes:
      - sms-pgdata:/var/lib/postgresql/data

  sms-service:
    build:
      context: ./sms-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/smsdb
      - QUARKUS_DATASOURCE_USERNAME=smsuser
      - QUARKUS_DATASOURCE_PASSWORD=smspass
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
      - postgres

  processor-service:
    build:
      context: ./processor-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SMS_SERVICE_CALLBACK_URL=http://sms-service:8080/sms/callback

    depends_on:
      - kafka
      - sms-service

volumes:
  sms-pgdata:
